### ISSUE TITLE
Remove approvers without categories

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/PageApprovals#101]
![image](https://github.com/user-attachments/assets/99859457-3b3b-438e-a7f9-aad06e7b3653)

AC: no approvers without categories show when loading the page

Optional:
* Removal from DB

Don't do
* Dynamic/live (UI) removal of the approver upon deletion of the last category

**Comment by malberts** [comment]
> Dynamic/live removal upon deletion of the last category (actually not clear this would improve the UX)

I suspect this will not be good. If I added a wrong category and remove it, then I don't expect the entire row to disappear.

**Comment by waximabbax** [comment]
> I suspect this will not be good. If I added a wrong category and remove it, then I don't expect the entire row to disappear.

We also have to show this when the user just added the username. Otherwise, we won't be able to add categories for new users. 

I think it's probably better to add a delete button for the user for the cleanup.

Anyhow, here is the PR using the description in the ticket:

https://github.com/ProfessionalWiki/PageApprovals/pull/111

This doesn't handle cases where the user adds multiple users quickly without adding categories and then wants to add categories for each user later. We may have older users in the table without categories, and it would be weird to suddenly show all the users without categories when the user adds a new user. Please look at the video to understand what I am talking about.

**We don't have a method for deleting the approver, but it can be created.
I think, at this point, it's cleaner to add Rest API for Adding and Deleting Categories.**

**Comment by JeroenDeDauw** [comment]
Let's not refactor towards REST now. It's already working, and it's not a trivial refactor.

**Comment by waximabbax** [comment]
Closed by:

https://github.com/ProfessionalWiki/PageApprovals/pull/111
